### ISSUE TITLE
Fatal Exception: NPE onMessageReceive

### ISSUE THREAD

**Issue by Karlos174** [customerio/customerio-android#145]
**SDK version:** 3.1.0
**Environment:** Production

**Are logs available?**
`Fatal Exception: java.lang.NullPointerException: null cannot be cast to non-null type io.customer.messagingpush.MessagingPushModuleConfig
       at java.util.Objects.requireNonNull(Objects.java:228)
       at io.customer.messagingpush.di.DiGraphMessagingPushKt.getModuleConfig(DiGraphMessagingPush.kt:23)
       at io.customer.messagingpush.CustomerIOPushNotificationHandler.getModuleConfig(CustomerIOPushNotificationHandler.kt:62)
       at io.customer.messagingpush.CustomerIOPushNotificationHandler.handleNotification(CustomerIOPushNotificationHandler.kt:198)
       at io.customer.messagingpush.CustomerIOPushNotificationHandler.handleMessage(CustomerIOPushNotificationHandler.kt:105)
       at io.customer.messagingpush.CustomerIOFirebaseMessagingService$Companion.handleMessageReceived(CustomerIOFirebaseMessagingService.kt:56)
       at io.customer.messagingpush.CustomerIOFirebaseMessagingService$Companion.onMessageReceived(CustomerIOFirebaseMessagingService.kt:31)
       at io.customer.messagingpush.CustomerIOFirebaseMessagingService$Companion.onMessageReceived$default(CustomerIOFirebaseMessagingService.kt:27)
       at io.customer.messagingpush.CustomerIOFirebaseMessagingService$Companion.onMessageReceived(CustomerIOFirebaseMessagingService.kt:8)
       at cz.ai.aschool.movies.fcm.FirebaseMessagingServiceMooveez.onMessageReceived(FirebaseMessagingServiceMooveez.java:99)` 

**Describe the bug**
After upgrade from customer io 2.1.1 to 3.1.0 Firebase Push Notification causes crash of our app.
I can provide you e-mails and times when crash occured.
Code in our class FirebaseMessagingServiceMooveez only bypasses RemoteMessage received.

**Comment by Shahroz16** [comment]
Hey @Karlos174, thanks for writing in. This is weird, I am looking into it. Will you be able to easily share the `FirebaseMessagingServiceMooveez.onMessageReceived()` method, so we can see how you are interacting with the SDK?

**Comment by Karlos174** [comment]
Only passing. Here you can see relevant code fragment.

![image](https://user-images.githubusercontent.com/116342887/197159346-b1d08461-5575-43ef-beb9-c4adbc96b287.png)

**Comment by Karlos174** [comment]
Sorry, we missed migration guide. Call of addCustomerIOModule is missing.
