### ISSUE TITLE
ANR io.customer.sdk.util.AndroidSimpleTimer.timerDone Input dispatching timed out

### ISSUE THREAD

**Issue by ciprian-cotoara-bokadirekt** [customerio/customerio-android#160]
**SDK version:** v3.1.1

**Environment:** Production

**Are logs available?** 
```
main (blocked):tid=1 systid=32402 | waiting to lock <0x0844ef67> (ic.b) held by thread 95
       at io.customer.sdk.util.AndroidSimpleTimer.timerDone(AndroidSimpleTimer.java:73)
       at io.customer.sdk.util.AndroidSimpleTimer.access$timerDone(AndroidSimpleTimer.java:21)
       at io.customer.sdk.util.AndroidSimpleTimer$scheduleAndCancelPrevious$1$newTimer$1$1.onFinish(SimpleTimer.kt:47)
       at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:142)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
```
DefaultDispatcher-worker-11 (blocked):tid=95 systid=3863 | waiting to lock <0x06f58114> (ic.a$a) held by thread 1
       at android.os.CountDownTimer.cancel(CountDownTimer.java)
       at io.customer.sdk.util.AndroidSimpleTimer.unsafeCancel(SimpleTimer.kt:97)
       at io.customer.sdk.util.AndroidSimpleTimer.cancel(SimpleTimer.kt:83)
       at io.customer.sdk.queue.QueueImpl.run(Queue.kt:106)
       at io.customer.sdk.queue.QueueImpl$runAsync$1.invokeSuspend(Queue.kt:124)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Describe the bug**
This randomly happens on different device brands and OS versions ranging from SDK 28 to 33.

**To Reproduce**

**Expected behavior**
The library should not be causing an ANR.

**Screenshots**

**Additional context**

**Comment by Shahroz16** [comment]
Hey @ciprian-cotoara-bokadirekt, thanks for writing to us, we will be looking into to see what might be the cause be.

**Comment by Shahroz16** [comment]
@ciprian-cotoara-bokadirekt we tried multiple times reproducing it but weren't able to do so. We plan to rewrite and optimize the whole background queuing but it's part of future releases. If you could provide any reproduction steps it would be super helpful.
