### ISSUE TITLE
Encountering numerous ANR at EngineWebView.<init>

### ISSUE THREAD

**Issue by shawn-lin-013** [customerio/customerio-android#300]
**SDK version:**
3.8.2

**Environment:** Development or Production
Production

```
main (native):tid=1 systid=29681 
#00 pc 0x5c070 libc.so (syscall + 28) (BuildId: 9f6570f91277a4c38fd5ce53a30061ae)
#01 pc 0x251d97 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 86) (BuildId: 590aedf23e5d581a4e04a2e06fbf0388)
#02 pc 0x575ef3 libart.so (artJniMethodEnd + 326) (BuildId: 590aedf23e5d581a4e04a2e06fbf0388)
#03 pc 0xf4c49 libart.so (art_jni_method_end + 8) (BuildId: 590aedf23e5d581a4e04a2e06fbf0388)
       at J.N.M1Y_XVCN(Native method)
       at org.chromium.content.browser.BrowserStartupControllerImpl.d(chromium-TrichromeWebViewGoogle.aab-stable-631209930:110)
       at WV.h5.run(chromium-TrichromeWebViewGoogle.aab-stable-631209930:180)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at org.chromium.base.task.PostTask.d(chromium-TrichromeWebViewGoogle.aab-stable-631209930:11)
       at org.chromium.android_webview.AwBrowserProcess.j(chromium-TrichromeWebViewGoogle.aab-stable-631209930:32)
       at com.android.webview.chromium.E.d(chromium-TrichromeWebViewGoogle.aab-stable-631209930:188)
       at com.android.webview.chromium.E.b(chromium-TrichromeWebViewGoogle.aab-stable-631209930:42)
       at com.android.webview.chromium.E.f(chromium-TrichromeWebViewGoogle.aab-stable-631209930:4)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.l(chromium-TrichromeWebViewGoogle.aab-stable-631209930:8)
       at com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle.aab-stable-631209930:97)
       at android.webkit.WebView.<init>(WebView.java:443)
       at android.webkit.WebView.<init>(WebView.java:363)
       at android.webkit.WebView.<init>(WebView.java:345)
       at android.webkit.WebView.<init>(WebView.java:332)
       at android.webkit.WebView.<init>(WebView.java:322)
       at io.customer.messaginginapp.gist.presentation.engine.EngineWebView.<init>(EngineWebView.kt:34)
       at io.customer.messaginginapp.gist.presentation.engine.EngineWebView.<init>(EngineWebView.kt:20)
       at io.customer.messaginginapp.gist.presentation.GistView.<init>(GistView.kt:27)
       at io.customer.messaginginapp.gist.presentation.GistSdk.init$lambda$0(GistSdk.kt:106)
       at android.os.Handler.handleCallback(Handler.java:978)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.app.ActivityThread.main(ActivityThread.java:8103)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

**Comment by levibostian** [comment]
Thanks for sending this to us, Shawn. 

To help us reproduce this issue, could you answer these questions to provide us with more context? 

* If you're able to reproduce this crash in your app, what steps do you perform in your app to trigger this crash? 
* If you're using a crash reporting tool such as Crashlytics to gather this stacktrace, is there a specific Android device that this is crashing on? 
* Is this happening for all of your app users or only some? 
* What line of code is called last in your app before you see this crash occur? We would appreciate if you send us this code block. 
* Is this a new behavior you're seeing or has it always been happening? What version is this crash happening for and what versions is it not happening for? 

Any other context that would help us reproduce this issue would be greatly appreciated. 

It's understandable that some of these answers have sensitive information inside of it. Feel free to send those answers to `win@customer.io` and in the email, link to this github issue. The team will route the message appropriately when they receive it.
